application: new-dbms
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static
  static_dir: static
- url: /css
  static_dir: css
- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts
- url: /images
  static_dir: images
- url: /img
  static_dir: img
- url: /table_filter
  static_dir: table_filter


- url: /.*
  script: index.app

- url: /.*
  script: new-dbms.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest